words:
    resource: "CrossWordApiBundle/Controller/WordsController"
    type:     rest
    prefix:   /api

fallback:
    path: /{url}
    defaults: { _controller: CrossWordApiBundle:Default:index, url: null }
    requirements:
        url: .*